source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.3', '>= 6.0.3.4'
gem 'mysql2', '0.5.2'
gem 'dotenv-rails', '2.7.5'
gem 'puma', '~> 4.1'
gem 'jbuilder', '~> 2.7'
gem 'fast_jsonapi', '1.5'
# gem 'redis', '~> 4.0'
# gem 'bcrypt', '~> 3.1.7'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', '4.0.1'
  # Linters
  gem 'rubocop', '1.3.0', require: false
  gem 'rubocop-performance', '1.9.1', require: false
  gem 'rubocop-rails', '2.8.1', require: false
  gem 'factory_bot_rails', '5.1.0'
  gem 'test-prof', '0.12.0'
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'shoulda-matchers', '4.4.0'
  gem 'simplecov', '0.20.0', require: false
end
